# This is a basic workflow to help you get started with Actions

name: kaka

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"

      - name: Setup Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run with retry
        uses: nick-fields/retry@v3
        env:
          V1: ${{ secrets.V1 }}
          V2: ${{ secrets.V2 }}
          V3: ${{ secrets.V3 }}
        with:
          timeout_minutes: 1
          max_attempts: 5
          retry_wait_seconds: 60
          retry_on: error
          command: python main.py


      - name: Push
        run: |
          git config --global user.name "nobody"
          git config --global user.email "nobody@gmail.com"
          git add -A
          git commit -m $(date '+%Y-%m-%d_%H%M%S')
          git push
